version: '3.8'
services:
  mongo:
    image: 'mongo:7.0.5'
    restart: always
    ports:
      - "27017:27017"
    command: mongod --port 27017 --bind_ip 0.0.0.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=NuMX)J~&\4KRBg&r_E|.
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
